version: '3.5'
services:
  cache:
    image: redis:7.2-alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.3GB"
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
  db:
    image: mongo:7.0.1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"
    environment:
      - MAX_POOL_SIZE=2000
    ports:
      - '27017:27017'
  web:
    build: ./
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: "2.3GB"
    ports:
      - "9999:9999"
    depends_on:
      - cache
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=postgres
      - DB_SCHEMA=rinha
      - REDIS_HOST=cache
      - REDIS_PORT=6379
